spring.application.name=chatserver
server.port=8081

# Used for the connection with docker mapped to thsi port to be able to connect to the database
spring.datasource.url=jdbc:postgresql://localhost:5433/chatserver
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

#jpa settings used to match entities to tables and crash if mismatch to catch errors and print SQL queires to the console so we can see what JPA is doing
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



#Flyway tells spring to run flyway migrations on app startup
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5433/chatserver
spring.flyway.locations=classpath:db/migration
spring.flyway.user=postgres
spring.flyway.password=secret

app.jwt.secret=ThisIsADevelopmentSecretKeyMakeItLongerAndRandomInProduction12345
app.jwt.expiration-ms=86400000

# Redis: labelling the hsot and port 
spring.data.redis.host=localhost
spring.data.redis.port=6379