services:
  # Postgres Database
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: chatserver
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  #Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  
  #Actual Spring App
  app:
    build: .
    ports:
     - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/chatserver
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ThisIsADevelopmentSecretKeyThisShouldBeLongerWhenItIsInProduction
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    

volumes:
  pgdata:
